### PR TITLE
Update pom and files to fix build

### PR DESCRIPTION
**Pull request by slide**
- Updated to new parent pom
- Fixed repositories to https
- Removed override of maven-release-plugin version
- Added jelly escape to files that were missing it

### CODE REVIEW

**Comment by jlelli** [comment]
Nice! I was just struggling to ``mvn install`` master! :-)
With this a can successfully generate the hpi.
Now let's see if [the issue](https://github.com/jenkinsci/validating-string-parameter-plugin/pull/9#issuecomment-372389804) I'm seeing is still present.

**Comment by jlelli** [comment]
So, local build of this PR successfully installed, but I'm still seeing the issue above: even if validation show problem with a parameter, I can still hit "Build" and start a Pipeline (when I already know that build is going to fail). Any help with this?
Thanks!

**Comment by jlelli** [comment]
> Is there a JIRA associated with the issue?

https://issues.jenkins-ci.org/browse/JENKINS-23951

Something along [this](https://github.com/jenkinsci/validating-string-parameter-plugin/pull/9/commits/46e2b086c5d2b08280653ab026267bd0d173ab3f#diff-7f2cc2852df243adfa24654a14dc3d5cR80) seems to at least correctly stop a build (we don't get a very informative error message back though :-/).

**Comment by jlelli** [comment]
> I don't maintain this plugin, I have just contributed some fixes

@slide and I appreciate this.. but since we are here.. ;-)

**Comment by jlelli** [comment]
Hey. Any luck in getting this merged?

**Comment by slide** [comment]
@Vlatombe are you still maintaining this plugin?

**Comment by Vlatombe** [comment]
@slide I don't.

**Comment by jlelli** [comment]
What about @petehayes then? :-)

**Pull request merged**
